### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by kraw-ios** [joeypatino/swiftvision#2]
Hey,
I'm trying to compile the demo project however I get the following error:

<img width="1245" alt="Screenshot 2023-05-30 at 14 58 33" src="https://github.com/joeypatino/swiftvision/assets/42810792/938ebc0e-a075-4340-be51-f446a8495581">

Do you have any clue? 
Thanks for the help!

**Comment by joeypatino** [comment]
Hey, thanks for the note. This might be caused by the framework file being stored using [Git LFS](https://git-lfs.com). Could you try to clone again after installing Git LFS, using the following command:

```
git lfs clone git@github.com:joeypatino/swiftvision.git
```

let me know if this works and I'll update the readme to add this as a prerequisite. If this doesn't help let me know and I'll try and repro the issue and come up with a solution.

Also, what type of Mac are you on? Apple Chip or Intel?

**Comment by kraw-ios** [comment]
Yes I was able to compile it correctly after cloning with LFS files, thanks for the fast response and for the help.
